### ISSUE TITLE
empty repository

### ISSUE THREAD

**Issue by Sh1ne111** [alethere/mpQTL#1]
Hello,
I recently read your article, "Multiallelic models for QTL mapping in diverse polyploid populations," published in BMC Bioinformatics. I was interested in testing your method, but I noticed that the GitHub repository appears to be empty. Would it be possible for you to make the repository public so that I can access the necessary materials to run the analysis?

Thank you for your time and for sharing your research.

Best wishes,
Chen

**Comment by alethere** [comment]
Hello Chen,

Thanks for bringing this to my attention. I’ve been doing some maintenance on the github which resulted in having to empty the repository. Originally it was supposed to be empty only for a few days but this has been somewhat prolonged. In the coming week I’ll have time to sort this issue, will let you know once it’s resolved.

Kind regards,

Alejandro

**Comment by alethere** [comment]
Hi Chen,

I managed to repair the repository. You should now be able to install the package as described in the README file.

Cheers,
Alejandro

**Comment by Sh1ne111** [comment]
Hi, alethere,

I want to test this tool, but I don't have genetic map, only have poly genotype and phenotype data.  What should I do?

**Comment by alethere** [comment]
Hi Shuai,
Do you at least know the order of your markers? I think the best is to give some reasonable order for your markers, and put each at a distance of 1.

However, interpreting the results may be difficult...

Regards,
Alejandro

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
