### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Oracle6543** [alethere/mpQTL#2]
> devtools::install_github("alethere/mpqtl")
Downloading GitHub repo alethere/mpqtl@HEAD
Error: Failed to install 'mpQTL' from GitHub:
  input string 1 is invalid
In addition: Warning message:
In gsub("\n([^[:blank:]])", "\n \\1", val) : unable to translate 'c(
    person("Giorgio", "Tumino", email = "giorgio.tumino@wur.nl",
           role = c("aut", "cre"), comment = c(ORCID = "0000-0002-6505-7652")),
    person("Alejandro", "Th<e9>r<e8>se Navarro", email = "alejandro.theresenavarro@wur.nl",
           r...' to a wide string

There is installation problem.. 
How can I solve this problem?
My R version is 4.3.1, and I also activate devtools package

Thanks.

**Comment by alethere** [comment]
Hi there, 
I'm not sure why that may be happening. Perhaps it is something to do with my name and the fact that it has some characters with accents. I have removed them, could you try to install it now and let me know if it works.

**Comment by Oracle6543** [comment]
It works! Thanks :)
